/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistemacaja;
import Clases.ImagenFondo;
import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
/**
 *
 * @author STARK
 */
public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
        JDEscritorio.setBorder(new ImagenFondo());
        this.setExtendedState(this.MAXIMIZED_BOTH);
        PDetail.setColorPrimario(new Color(0, 0, 0, 50));
        PDetail.setColorSecundario(new Color(0, 0, 0, 50));
        LblEstado.setBackground(new Color(0, 0, 0, 50));
        setTitle("BIENVENIDO AL SISTEMA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panel1 = new org.edisoncor.gui.panel.Panel();
        LblEstado = new javax.swing.JLabel();
        PImagenUsuario = new org.edisoncor.gui.panel.PanelImage();
        LblUsuario = new org.edisoncor.gui.label.LabelMetric();
        PDetail = new org.edisoncor.gui.panel.Panel();
        LblNacimiento = new javax.swing.JLabel();
        LblProfesion = new javax.swing.JLabel();
        LblUniversidad = new javax.swing.JLabel();
        JDEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMArchivo = new javax.swing.JMenu();
        JMISesion = new javax.swing.JMenuItem();
        JMISalir = new javax.swing.JMenuItem();
        JMRecibos = new javax.swing.JMenu();
        JMISolicitud = new javax.swing.JMenuItem();
        JMIDNI = new javax.swing.JMenuItem();
        JMReportes = new javax.swing.JMenu();
        JMIDiario = new javax.swing.JMenuItem();
        JMIMensual = new javax.swing.JMenuItem();
        JMAjustes = new javax.swing.JMenu();
        JMIAnular = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siscajaImagenes/fondo (1).jpg"))); // NOI18N
        panelImage1.setPreferredSize(new java.awt.Dimension(242, 710));
        panelImage1.setLayout(new java.awt.BorderLayout());

        panel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 153, 255)));
        panel1.setPreferredSize(new java.awt.Dimension(242, 710));

        LblEstado.setBackground(new java.awt.Color(0, 102, 153));
        LblEstado.setFont(new java.awt.Font("AgencyFB", 0, 18)); // NOI18N
        LblEstado.setForeground(new java.awt.Color(0, 255, 0));
        LblEstado.setText(">> ON-LINE USER");
        LblEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 1, true));

        PImagenUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 1, true));
        PImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuarios/default1.png"))); // NOI18N
        PImagenUsuario.setMaximumSize(new java.awt.Dimension(222, 273));
        PImagenUsuario.setMinimumSize(new java.awt.Dimension(222, 273));

        javax.swing.GroupLayout PImagenUsuarioLayout = new javax.swing.GroupLayout(PImagenUsuario);
        PImagenUsuario.setLayout(PImagenUsuarioLayout);
        PImagenUsuarioLayout.setHorizontalGroup(
            PImagenUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PImagenUsuarioLayout.setVerticalGroup(
            PImagenUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        LblUsuario.setText("VILMA ");
        LblUsuario.setDistanciaDeSombra(2);
        LblUsuario.setFont(new java.awt.Font("AgencyFB", 0, 24)); // NOI18N

        PDetail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 1, true));
        PDetail.setMaximumSize(new java.awt.Dimension(222, 264));
        PDetail.setMinimumSize(new java.awt.Dimension(222, 264));

        LblNacimiento.setBackground(new java.awt.Color(0, 102, 153));
        LblNacimiento.setFont(new java.awt.Font("AgencyFB", 0, 18)); // NOI18N
        LblNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        LblNacimiento.setText("Nacido en Siberia, en 1990-01-01.");
        LblNacimiento.setMaximumSize(new java.awt.Dimension(200, 22));
        LblNacimiento.setMinimumSize(new java.awt.Dimension(200, 22));
        LblNacimiento.setPreferredSize(new java.awt.Dimension(200, 22));

        LblProfesion.setBackground(new java.awt.Color(0, 102, 153));
        LblProfesion.setFont(new java.awt.Font("AgencyFB", 0, 18)); // NOI18N
        LblProfesion.setForeground(new java.awt.Color(255, 255, 255));
        LblProfesion.setText("Graduado en Forensica Informatica.");
        LblProfesion.setMaximumSize(new java.awt.Dimension(200, 22));
        LblProfesion.setMinimumSize(new java.awt.Dimension(200, 22));
        LblProfesion.setPreferredSize(new java.awt.Dimension(200, 22));

        LblUniversidad.setBackground(new java.awt.Color(0, 102, 153));
        LblUniversidad.setFont(new java.awt.Font("AgencyFB", 0, 18)); // NOI18N
        LblUniversidad.setForeground(new java.awt.Color(255, 255, 255));
        LblUniversidad.setText("Graduado en Forensica Informatica.");
        LblUniversidad.setMaximumSize(new java.awt.Dimension(200, 22));
        LblUniversidad.setMinimumSize(new java.awt.Dimension(200, 22));
        LblUniversidad.setPreferredSize(new java.awt.Dimension(200, 22));

        javax.swing.GroupLayout PDetailLayout = new javax.swing.GroupLayout(PDetail);
        PDetail.setLayout(PDetailLayout);
        PDetailLayout.setHorizontalGroup(
            PDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblUniversidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblProfesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PDetailLayout.setVerticalGroup(
            PDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel1Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PImagenUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(PImagenUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(LblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(PDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelImage1.add(panel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout JDEscritorioLayout = new javax.swing.GroupLayout(JDEscritorio);
        JDEscritorio.setLayout(JDEscritorioLayout);
        JDEscritorioLayout.setHorizontalGroup(
            JDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        JDEscritorioLayout.setVerticalGroup(
            JDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JMArchivo.setText("Archivo");

        JMISesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/user_12x16.png"))); // NOI18N
        JMISesion.setText("Nueva Sesion");
        JMISesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMISesionActionPerformed(evt);
            }
        });
        JMArchivo.add(JMISesion);

        JMISalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir.png"))); // NOI18N
        JMISalir.setText("Salir");
        JMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMISalirActionPerformed(evt);
            }
        });
        JMArchivo.add(JMISalir);

        jMenuBar1.add(JMArchivo);

        JMRecibos.setText("Recibos");

        JMISolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/glyphicons_029_notes_2.png"))); // NOI18N
        JMISolicitud.setText("Solicitud");
        JMISolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMISolicitudActionPerformed(evt);
            }
        });
        JMRecibos.add(JMISolicitud);

        JMIDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/glyphicons_353_nameplate_alt.png"))); // NOI18N
        JMIDNI.setText("DNI");
        JMIDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIDNIActionPerformed(evt);
            }
        });
        JMRecibos.add(JMIDNI);

        jMenuBar1.add(JMRecibos);

        JMReportes.setText("Reportes");

        JMIDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/print.png"))); // NOI18N
        JMIDiario.setText("Diario");
        JMIDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIDiarioActionPerformed(evt);
            }
        });
        JMReportes.add(JMIDiario);

        JMIMensual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/calendar.png"))); // NOI18N
        JMIMensual.setText("Mensual");
        JMReportes.add(JMIMensual);

        jMenuBar1.add(JMReportes);

        JMAjustes.setText("Ajustes");

        JMIAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/postits.png"))); // NOI18N
        JMIAnular.setText("Anular Recibos");
        JMIAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIAnularActionPerformed(evt);
            }
        });
        JMAjustes.add(JMIAnular);

        jMenuBar1.add(JMAjustes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(JDEscritorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, Short.MAX_VALUE)
            .addComponent(JDEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void asiganarlugar(){
        panelImage1.setSize(242, this.getHeight());
        panelImage1.setLocation(this.getWidth()-(panelImage1.getWidth()+16), 0);
       JDEscritorio.setSize(this.getWidth()-(panelImage1.getWidth()+16),this.getHeight());
       panel1.setColorPrimario(new Color(0, 0, 0, 10));
       panel1.setColorSecundario(new Color(0, 0, 0, 10));
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        panelImage1.setSize(242, this.getHeight());
        panelImage1.setLocation(this.getWidth()-(panelImage1.getWidth()+16), 0);
       JDEscritorio.setSize(this.getWidth()-(panelImage1.getWidth()+16),this.getHeight());
       panel1.setColorPrimario(new Color(0, 0, 0, 10));
       panel1.setColorSecundario(new Color(0, 0, 0, 10));
    }//GEN-LAST:event_formWindowOpened

    private void JMIDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIDiarioActionPerformed
        try {
            // TODO add your handling code here:
            ///String fecha = JOptionPane.showInputDialog(rootPane, "Ingrese Fecha (Año-Mes-dia)");
            //jasper.ejecutarReporte(fecha);
            Desktop.getDesktop().browse(new URI("http://192.168.1.100/reportesDiarios"));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JMIDiarioActionPerformed

    private void JMISolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMISolicitudActionPerformed
//        dialogRecSolicitud solic = new dialogRecSolicitud(this, false);
//        solic.setVisible(true);
        JIFRecSolicitud RecSolicitud = new JIFRecSolicitud();
        JDEscritorio.add(RecSolicitud);
        RecSolicitud.show();
    }//GEN-LAST:event_JMISolicitudActionPerformed

    private void JMIDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIDNIActionPerformed
//        dialogRecDNI solic = new dialogRecDNI(this, false);
//       solic.setVisible(true);
        JIFRecDNI RecDNI = new JIFRecDNI();
        JDEscritorio.add(RecDNI);
        RecDNI.show();
    }//GEN-LAST:event_JMIDNIActionPerformed

    private void JMIAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIAnularActionPerformed
//        frmAnular anular = new frmAnular(this, true);
//        anular.setVisible(true);
//        dispose();
        new frmAnular(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_JMIAnularActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
         panelImage1.setSize(242, this.getHeight());
        panelImage1.setLocation(this.getWidth()-(panelImage1.getWidth()+16), 0);
        JDEscritorio.setSize(this.getWidth()-(panelImage1.getWidth()+16),this.getHeight());
    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         panelImage1.setSize(242, this.getHeight());
        panelImage1.setLocation(this.getWidth()-(panelImage1.getWidth()+16), 0);
        JDEscritorio.setSize(this.getWidth()-(panelImage1.getWidth()+16),this.getHeight());
    }//GEN-LAST:event_formWindowActivated

    private void JMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMISalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMISalirActionPerformed

    private void JMISesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMISesionActionPerformed
        new frmLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_JMISesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane JDEscritorio;
    private javax.swing.JMenu JMAjustes;
    private javax.swing.JMenu JMArchivo;
    private javax.swing.JMenuItem JMIAnular;
    private javax.swing.JMenuItem JMIDNI;
    private javax.swing.JMenuItem JMIDiario;
    private javax.swing.JMenuItem JMIMensual;
    private javax.swing.JMenuItem JMISalir;
    private javax.swing.JMenuItem JMISesion;
    private javax.swing.JMenuItem JMISolicitud;
    private javax.swing.JMenu JMRecibos;
    private javax.swing.JMenu JMReportes;
    public static javax.swing.JLabel LblEstado;
    public static javax.swing.JLabel LblNacimiento;
    public static javax.swing.JLabel LblProfesion;
    public static javax.swing.JLabel LblUniversidad;
    public static org.edisoncor.gui.label.LabelMetric LblUsuario;
    public static org.edisoncor.gui.panel.Panel PDetail;
    public static org.edisoncor.gui.panel.PanelImage PImagenUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    public static org.edisoncor.gui.panel.Panel panel1;
    public static org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
